/*
 * uartbuf-board.c
 *
 *  Created on: 23.01.2018
 *      Author: kamil
 */

#include "uartbuf.h"

#include "utilities.h"
#include "hal.h"
#include "error_handler.h"

#include <assert.h>

inline
void uartbufrx_EnableIRQ_Callback(const struct uartbufrx_s *t)
{
	NVIC_EnableIRQ(t->priv.IRQn);
}

inline
void uartbufrx_DisableIRQ_Callback(const struct uartbufrx_s *t)
{
	NVIC_DisableIRQ(t->priv.IRQn);
}

inline
bool uartbufrx_IsReceiving_Callback(const struct uartbufrx_s *t)
{
	//return !HAL_UART_IsReceiveReady(t->priv.huart);
	return !( t->priv.huart->RxState == HAL_UART_STATE_READY );
}

inline
void uartbufrx_ArmReceive_Callback(struct uartbufrx_s *t, uint8_t buf[], size_t size)
{

	assert(t->priv.maxchunk);
	if ( !size ) { return; }
	const size_t chunk = MIN(size, t->priv.maxchunk);
	uartbufrx_DisableIRQ_Callback(t);
	if ( HAL_UART_Receive_DMA(t->priv.huart, buf, chunk) != HAL_OK ) {
		volatile uint8_t *_buf = buf;
		volatile size_t _size = size;
		volatile size_t _chunk = chunk;
		volatile struct uartbufrx_s * _t = t;
		__BKPT(0);
		_Error_Handler(/*autogenerated*/ 26 );
	}
	uartbufrx_EnableIRQ_Callback(t);
}

void uartbufrx_waitfor_buflen_Callback(const struct uartbufrx_s *t, size_t num)
{
	HAL_PWR_EnterSLEEPMode(PWR_MAINREGULATOR_ON, PWR_SLEEPENTRY_WFI);
}

inline
void uartbuftx_EnableIRQ_Callback(const struct uartbuftx_s *t)
{
	NVIC_EnableIRQ(t->priv.IRQn);
}

inline
void uartbuftx_DisableIRQ_Callback(const struct uartbuftx_s *t)
{
	NVIC_DisableIRQ(t->priv.IRQn);
}

inline
bool uartbuftx_IsWriting_Callback(const struct uartbuftx_s *t)
{
	return !HAL_UART_IsTransmitReady(t->priv.huart);
}

inline
void uartbuftx_Write_Callback(struct uartbuftx_s *t, const uint8_t buf[], size_t size)
{
	t->priv.size = size;
	if ( !size ) { return; }
	uartbuftx_DisableIRQ_Callback(t);
	if ( HAL_UART_Transmit_DMA(t->priv.huart, (uint8_t*)buf, size) != HAL_OK ) {
		_Error_Handler(/*autogenerated*/ 28 );
	}
	uartbuftx_EnableIRQ_Callback(t);
}

inline
void uartbuftx_Flush_Callback(const struct uartbuftx_s *t)
{
	HAL_PWR_EnterSLEEPMode(PWR_MAINREGULATOR_ON, PWR_SLEEPENTRY_WFI);
}
